// — Demo seed data for Inbox & Reviews ----------------------------------------
const daysAgo = n => new Date(Date.now() - n*86400000).toISOString();

export const DEMO_THREADS = [
  { id:"t1", name:"Jane Whitfield", project:"Kitchen remodel — phase 2", unread:true, messages:[
    { id:"m1", from:"client", text:"Hi! I saw your portfolio and love the tile work on that bathroom remodel. Are you available to take a look at our kitchen sometime this week?", at:daysAgo(1.4) },
    { id:"m2", from:"client", text:"Also wanted to ask — do you handle the plumbing rerouting yourself or bring in a sub for that?", at:daysAgo(1.3) },
  ]},
  { id:"t2", name:"Marcus Lee", project:"Roof inspection — rental property", unread:true, messages:[
    { id:"m3", from:"client", text:"Thanks for the quick quote yesterday. Just confirming — does the price include disposal of the old shingles?", at:daysAgo(0.6) },
  ]},
  { id:"t3", name:"Priya Shah", project:"Bathroom vanity install", unread:false, messages:[
    { id:"m4", from:"client", text:"The vanity arrived today, a day early actually. Let me know what date works for install.", at:daysAgo(3) },
    { id:"m5", from:"me", text:"That's great news! I have an opening Thursday afternoon — does 1pm work for you?", at:daysAgo(2.8) },
    { id:"m6", from:"client", text:"Thursday at 1pm works perfectly. See you then!", at:daysAgo(2.7) },
  ]},
];

export const DEMO_REVIEWS = [
  { id:"r1", name:"Jennifer Cole", rating:5, project:"Full bathroom remodel", text:"Outstanding work from start to finish. Showed up on time every day, kept the workspace clean, and the final result looks better than what we pictured. Couldn't be happier.", date:daysAgo(12), response:"" },
  { id:"r2", name:"David Park", rating:5, project:"Roof replacement", text:"Professional, communicative, and the crew worked fast without cutting corners. Walked us through everything before starting and answered all our questions.", date:daysAgo(28), response:"Thank you David, it was a pleasure working on your home! Don't hesitate to reach out if you need anything down the road." },
  { id:"r3", name:"Monica Ruiz", rating:4, project:"Kitchen electrical upgrade", text:"Great work overall. Only minor issue was scheduling ran about a day longer than originally quoted, but the quality of the work made up for it.", date:daysAgo(45), response:"" },
  { id:"r4", name:"Tom Bradley", rating:5, project:"Flooring installation", text:"Second time using this contractor and once again everything went smoothly. Fair pricing, no surprises on the final invoice, and the floors look amazing.", date:daysAgo(60), response:"Appreciate you coming back to us, Tom — always a pleasure!" },
];

export const DEMO_CONTRACTORS = [
  { responseRate:96, responseTime:"within 2 hours", id:"demo1", name:"Marcus Webb", company:"Webb & Sons Roofing", city:"San Diego", state:"CA", bio:"Third-generation roofer with 22 years experience in residential and commercial roofing. We specialize in tile, shingle, and flat roof systems across San Diego County. Every job comes with a 10-year workmanship warranty.", trades:["Roofing","Framing"], licensed:true, insured:true, backgroundCheck:true, phone:"(619) 555-0142", email:"marcus@webbsonsroofing.com", website:"webbsonsroofing.com", licenseNum:"CA-887421", insurance:"Travelers · $2M liability", years:"22", serviceArea:"San Diego County — within 40 miles", rating:4.9, reviewCount:87, photos:[{ id:"dp1", src:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&q=80", caption:"Tile roof replacement — Mission Hills", category:"After" },{ id:"dp2", src:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", caption:"Flat roof — commercial building downtown", category:"After" }] },
  { responseRate:99, responseTime:"within 1 hour", id:"demo2", name:"Sofia Reyes", company:"Reyes Electric Co.", city:"Chula Vista", state:"CA", bio:"Licensed Master Electrician serving the greater San Diego area since 2010. Specializing in panel upgrades, EV charger installs, whole-home rewiring, and solar-ready electrical systems. We are a woman-owned small business.", trades:["Electrical","Insulation"], licensed:true, insured:true, backgroundCheck:true, phone:"(619) 555-0287", email:"sofia@reyeselectric.com", website:"reyeselectric.com", licenseNum:"CA-C10-449821", insurance:"Liberty Mutual · $3M liability", years:"14", serviceArea:"San Diego, Chula Vista, National City, Coronado", rating:5.0, reviewCount:52, photos:[{ id:"dp3", src:"https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&q=80", caption:"200A panel upgrade — Eastlake home", category:"After" }] },
  { responseRate:84, responseTime:"within 6 hours", id:"demo3", name:"Derrick Holloway", company:"SoCal HVAC Solutions", city:"El Cajon", state:"CA", bio:"NATE-certified HVAC technician with 18 years in the field. Full installation, replacement, and maintenance services for all major brands. We offer same-day emergency service and free estimates on system replacements.", trades:["HVAC"], licensed:true, insured:true, backgroundCheck:false, phone:"(619) 555-0391", email:"derrick@socalhvac.com", website:"socalhvac.com", licenseNum:"CA-C20-552113", insurance:"State Farm · $1M liability", years:"18", serviceArea:"East San Diego County — El Cajon, Santee, La Mesa, Lemon Grove", rating:4.7, reviewCount:134, photos:[{ id:"dp4", src:"https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400&q=80", caption:"Mini-split install — La Mesa condo", category:"After" }] },
  { responseRate:91, responseTime:"within 4 hours", id:"demo4", name:"Tomas Guerrero", company:"Guerrero Hardwood Flooring", city:"Escondido", state:"CA", bio:"Master craftsman specializing in hardwood installation, refinishing, and custom inlays. Over 15 years creating beautiful floors for homes and businesses throughout North County. Free in-home estimates with material samples.", trades:["Flooring","Painting"], licensed:true, insured:true, backgroundCheck:true, phone:"(760) 555-0178", email:"tomas@guerreroflooring.com", website:"", licenseNum:"CA-C15-312045", insurance:"Nationwide · $1.5M liability", years:"15", serviceArea:"North San Diego County — Escondido, Vista, San Marcos, Carlsbad", rating:4.8, reviewCount:63, photos:[{ id:"dp5", src:"https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=400&q=80", caption:"White oak install — Rancho Bernardo", category:"After" },{ id:"dp6", src:"https://images.unsplash.com/photo-1560185009-5bf9f837849a?w=400&q=80", caption:"Herringbone pattern — custom entry", category:"After" }] },
  { responseRate:98, responseTime:"within 1 hour", id:"demo5", name:"Angela Kim", company:"Kim Plumbing & Drain", city:"La Jolla", state:"CA", bio:"Licensed plumber offering complete residential and commercial plumbing services. Trenchless sewer repair, water heater replacement, kitchen and bath remodels, and 24/7 emergency drain clearing. Fully certified and background checked.", trades:["Plumbing"], licensed:true, insured:true, backgroundCheck:true, phone:"(858) 555-0044", email:"angela@kimplumbing.com", website:"kimplumbing.com", licenseNum:"CA-C36-198744", insurance:"Allstate · $2M liability", years:"11", serviceArea:"Coastal San Diego — La Jolla, Pacific Beach, Mission Valley, Point Loma", rating:4.9, reviewCount:201, photos:[{ id:"dp7", src:"https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80", caption:"Bathroom remodel rough-in — La Jolla", category:"In Progress" }] },
  { responseRate:79, responseTime:"within 8 hours", id:"demo6", name:"Brett Sandoval", company:"Sandoval Concrete & Masonry", city:"Oceanside", state:"CA", bio:"Concrete and masonry contractor specializing in driveways, stamped patios, retaining walls, and commercial flatwork. 20 years of precision work with a portfolio of 500+ completed projects throughout North County.", trades:["Concrete","Framing","Demolition"], licensed:true, insured:true, backgroundCheck:false, phone:"(760) 555-0522", email:"brett@sandovalconcrete.com", website:"sandovalconcrete.com", licenseNum:"CA-C8-771209", insurance:"Farmers · $2M liability", years:"20", serviceArea:"Oceanside, Carlsbad, Vista, Camp Pendleton area", rating:4.6, reviewCount:89, photos:[{ id:"dp8", src:"https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&q=80", caption:"Stamped concrete patio — Carlsbad", category:"After" }] },
];

export const MATCHED_CONTRACTORS = [
  // — ELECTRICAL --------------------------------------------------------------
  { id:"dc1",  initials:"MS", avatarBg:"#E6F1FB", avatarColor:"#0C447C", name:"Mike Sandoval",     company:"Sandoval Electric",              trades:["Electrical"],         city:"National City",  rating:5.0, reviewCount:47, years:22, licensed:true,  insured:true,  backgroundCheck:true,  bio:"San Diego native and C-10 licensed electrician specializing in residential panel upgrades, EV charger installation, and service upgrades. 22 years of clean, code-compliant work across South Bay.", highlights:["200-amp panel upgrades","EV charger installs (Level 2 & DCFC)","Service upgrades & rewires"], serviceArea:"South Bay — National City, Chula Vista, Bonita, San Diego" },
  { id:"dc2",  initials:"ST", avatarBg:"#E6F1FB", avatarColor:"#0C447C", name:"Sam Torres",        company:"Torres Electrical Services",     trades:["Electrical"],         city:"San Diego",      rating:4.7, reviewCount:34, years:14, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Licensed C-10 electrician covering Central San Diego and Mission Valley. Specialties include smart home wiring, recessed lighting, GFCI upgrades, and full home rewires for older properties.", highlights:["Smart home & Lutron wiring","Recessed lighting installs","Full rewires for older homes"], serviceArea:"Central San Diego, Mission Valley, North Park, Hillcrest, Kensington" },
  { id:"dc3",  initials:"RK", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Robert Kim",        company:"SunPath Solar & Electric",       trades:["Solar","Electrical"],  city:"San Diego",      rating:4.8, reviewCount:58, years:8,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Solar and electrical specialist with 8 years of San Diego rooftop systems. Every solar design is built around NEM 3.0 from day one — sized to maximize self-consumption, not just panel count.", highlights:["NEM 3.0 optimized system design","Powerwall & Enphase battery backup","SDG&E interconnection expert"], serviceArea:"San Diego, La Jolla, Pacific Beach, Mission Valley, Chula Vista" },

  // — HVAC --------------------------------------------------------------------
  { id:"dc4",  initials:"JW", avatarBg:"#E1F5EE", avatarColor:"#0F6E56", name:"Jennifer Walsh",    company:"Walsh HVAC Services",            trades:["HVAC"],               city:"Poway",          rating:4.8, reviewCount:41, years:13, licensed:true,  insured:true,  backgroundCheck:true,  bio:"C-20 licensed HVAC contractor and Lennox Premier Dealer serving North County for 13 years. We carry equipment in stock — most systems are installed within 48 hours of signing.", highlights:["Lennox Premier Dealer","Same-week installation","SEER2 high-efficiency systems"], serviceArea:"North County — Poway, Rancho Bernardo, Rancho Penasquitos, Mira Mesa" },
  { id:"dc5",  initials:"MR", avatarBg:"#E1F5EE", avatarColor:"#0F6E56", name:"Marco Reyes",       company:"Southwest HVAC Co.",             trades:["HVAC"],               city:"Chula Vista",    rating:4.7, reviewCount:38, years:11, licensed:true,  insured:true,  backgroundCheck:true,  bio:"HVAC specialist focused on residential central air replacement and mini-split installation in South Bay. Factory authorized for Daikin and Carrier systems with extended labor warranties on every job.", highlights:["Daikin & Carrier factory authorized","Mini-split & multi-zone systems","Free load calculation included"], serviceArea:"South Bay — Chula Vista, National City, Bonita, Imperial Beach" },
  { id:"dc6",  initials:"KT", avatarBg:"#E1F5EE", avatarColor:"#0F6E56", name:"Karen Tran",        company:"Cool Climate HVAC",              trades:["HVAC"],               city:"El Cajon",       rating:4.9, reviewCount:27, years:9,  licensed:true,  insured:true,  backgroundCheck:false, bio:"East County HVAC contractor specializing in energy-efficient system replacements and ductwork repair. SDG&E Qualified Contractor — we handle all rebate paperwork so you don't have to.", highlights:["SDG&E rebate paperwork handled","Ductwork seal & repair","Heat pump conversions"], serviceArea:"East County — El Cajon, Santee, Lakeside, Alpine, La Mesa" },

  // — PLUMBING ----------------------------------------------------------------
  { id:"dc7",  initials:"AL", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Angela Liu",        company:"Liu Plumbing Solutions",         trades:["Plumbing"],           city:"El Cajon",       rating:4.8, reviewCount:61, years:15, licensed:true,  insured:true,  backgroundCheck:false, bio:"Licensed C-36 plumber with 15 years of residential and light commercial experience in East County. Specialties include full PEX repiping, water heater replacement, and drain repair.", highlights:["PEX repiping specialist","Same-day water heater replacement","Tankless water heater installs"], serviceArea:"East County — El Cajon, Santee, La Mesa, Spring Valley" },
  { id:"dc8",  initials:"RV", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Roberto Vasquez",   company:"Vasquez Plumbing Co.",           trades:["Plumbing"],           city:"San Diego",      rating:4.7, reviewCount:49, years:16, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Central San Diego plumber specializing in bathroom remodels, fixture installation, and slab leak detection. Flat-rate pricing on most jobs — no surprise charges when the work is done.", highlights:["Slab leak detection & repair","Bathroom fixture installs","Flat-rate pricing model"], serviceArea:"Central San Diego, Mission Hills, North Park, South Park, Golden Hill" },
  { id:"dc9",  initials:"TO", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Tom O'Brien",       company:"O'Brien Drain & Pipe",           trades:["Plumbing"],           city:"Spring Valley",  rating:4.6, reviewCount:43, years:20, licensed:true,  insured:true,  backgroundCheck:false, bio:"20-year veteran plumber focused on drain cleaning, hydro-jetting, and sewer line work. Video camera inspection on every major job so homeowners see exactly what's happening underground.", highlights:["Hydro-jet drain clearing","Video camera pipe inspection","Sewer line repair & relining"], serviceArea:"South County — Spring Valley, Lemon Grove, Chula Vista, National City" },

  // — ROOFING -----------------------------------------------------------------
  { id:"dc10", initials:"JR", avatarBg:"#FCEBEB", avatarColor:"#A32D2D", name:"James Reyes",       company:"Reyes Roofing Co.",              trades:["Roofing"],            city:"Chula Vista",    rating:4.9, reviewCount:83, years:18, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Family-owned roofing company serving South Bay since 2006. Asphalt, tile, and metal roofing with a 10-year workmanship warranty — and a drone inspection report before every quote.", highlights:["10-year workmanship warranty","Asphalt, tile & metal roofs","Free drone roof inspection"], serviceArea:"South Bay — Chula Vista, National City, Bonita, Eastlake" },
  { id:"dc11", initials:"SO", avatarBg:"#FCEBEB", avatarColor:"#A32D2D", name:"Steve Okafor",      company:"Okafor Roofing & Sheet Metal",   trades:["Roofing"],            city:"Santee",         rating:4.7, reviewCount:49, years:17, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Certified by GAF, CertainTeed, and Owens Corning. Specializes in standing seam metal roofing and commercial TPO flat roofs — manufacturer-backed materials warranties on every install.", highlights:["GAF & CertainTeed certified","Metal & TPO flat roofing","Standing seam metal specialist"], serviceArea:"East County — Santee, El Cajon, Lakeside, Ramona, Alpine" },
  { id:"dc12", initials:"PN", avatarBg:"#FCEBEB", avatarColor:"#A32D2D", name:"Patricia Nguyen",   company:"Nguyen Roofing Systems",         trades:["Roofing"],            city:"San Diego",      rating:4.8, reviewCount:31, years:13, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Licensed C-39 roofer covering Central and North San Diego. Specializes in tile roof repair and full replacement — particularly experienced with the clay and concrete tile systems common in coastal SD neighborhoods.", highlights:["Clay & concrete tile specialist","Leak diagnosis & repair","Insurance claim assistance"], serviceArea:"Central SD, Hillcrest, North Park, La Jolla, Del Mar, Encinitas" },

  // — REMODEL -----------------------------------------------------------------
  { id:"dc13", initials:"DW", avatarBg:"#EEEDFE", avatarColor:"#534AB7", name:"David Williams",    company:"Williams Remodel Group",         trades:["Remodel"],            city:"Escondido",      rating:4.7, reviewCount:38, years:12, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Full-service remodeling contractor for kitchens, bathrooms, and whole-home renovations in North County. Design-first approach — we help homeowners make smart decisions before anything is demolished.", highlights:["Kitchen & bath remodels","Open concept conversions","3D design preview before demo"], serviceArea:"North County — Escondido, San Marcos, Vista, Poway, Carlsbad" },
  { id:"dc14", initials:"LC", avatarBg:"#EEEDFE", avatarColor:"#534AB7", name:"Lisa Chen",         company:"Chen Design + Build",            trades:["Remodel"],            city:"La Jolla",       rating:5.0, reviewCount:22, years:7,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"High-end design-build contractor for coastal San Diego remodels. Small firm with personal attention — Lisa is on every job site every day. Specializes in ADU additions and luxury kitchen renovations.", highlights:["Full-service design + build","Coastal permit & ADU specialist","Luxury finishes & custom millwork"], serviceArea:"La Jolla, Del Mar, Pacific Beach, Solana Beach, Encinitas" },
  { id:"dc15", initials:"DS", avatarBg:"#EEEDFE", avatarColor:"#534AB7", name:"Derek Santos",      company:"Santos Kitchen & Bath",          trades:["Remodel"],            city:"Encinitas",      rating:4.8, reviewCount:19, years:9,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Kitchen and bathroom remodel specialist serving Coastal North County. Every project comes with a fixed-price contract — no change orders unless the scope changes. Homeowners always know what they're paying.", highlights:["Fixed-price contracts","Kitchen & bath only — we specialize","Semi-custom cabinet installs"], serviceArea:"Coastal North County — Encinitas, Carlsbad, Solana Beach, Oceanside" },

  // — FLOORING ----------------------------------------------------------------
  { id:"dc16", initials:"EM", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Elena Morales",     company:"Morales Flooring Co.",           trades:["Flooring"],           city:"San Diego",      rating:4.8, reviewCount:44, years:8,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Flooring specialist covering San Diego and South Bay. Expertise in luxury vinyl plank, tile, and laminate — quick turnarounds with minimal disruption. Free in-home samples brought to you.", highlights:["LVP & laminate installs","Tile & grout work","Free in-home sample consultation"], serviceArea:"San Diego, Chula Vista, National City, Lemon Grove, La Mesa" },
  { id:"dc17", initials:"CN", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Chris Nakamura",    company:"Nakamura Hardwood Floors",       trades:["Flooring"],           city:"La Mesa",        rating:4.9, reviewCount:37, years:14, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Hardwood flooring specialist with 14 years of installs, refinishes, and repairs. Solid and engineered hardwood only — sand-and-finish refinishing brings worn floors back to life at a fraction of replacement cost.", highlights:["Hardwood install & refinish","Stair nose & transition work","Dustless sanding system"], serviceArea:"East County & Central SD — La Mesa, El Cajon, Santee, San Diego" },

  // — PAINTING ----------------------------------------------------------------
  { id:"dc18", initials:"TF", avatarBg:"#F8F7F4", avatarColor:"#2C2C2A", name:"Tony Ferrara",      company:"Ferrara Painting Co.",           trades:["Painting"],           city:"Santee",         rating:4.6, reviewCount:71, years:16, licensed:true,  insured:true,  backgroundCheck:false, bio:"Interior and exterior painting for homes and small commercial buildings. Premium paints formulated for San Diego's coastal salt air — no peeling, no fading, written guarantee on every exterior job.", highlights:["Premium exterior coatings","Stucco texture repair","Color consultation included"], serviceArea:"East County — Santee, El Cajon, San Carlos, Lakeside, Ramona" },
  { id:"dc19", initials:"JK", avatarBg:"#F8F7F4", avatarColor:"#2C2C2A", name:"Jim Kowalski",      company:"Kowalski Painting & Finishes",   trades:["Painting"],           city:"San Diego",      rating:4.7, reviewCount:58, years:18, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Full-service painting contractor for interior and exterior residential work across Central and North San Diego. Known for meticulous prep work — we fix what others paint over.", highlights:["Detailed surface prep & patching","Cabinet painting & refinishing","Multi-story exterior painting"], serviceArea:"Central & North SD — San Diego, Poway, Mira Mesa, Rancho Bernardo" },
  { id:"dc20", initials:"RM", avatarBg:"#F8F7F4", avatarColor:"#2C2C2A", name:"Rosa Martinez",     company:"Martinez Interior Painting",     trades:["Painting"],           city:"Chula Vista",    rating:4.8, reviewCount:26, years:7,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Interior painting specialist for South Bay homes and condos. Fast, clean, and reliable — most single-room jobs completed same day. Full home interiors typically done in 3 days. Perfect results or we come back.", highlights:["Same-day single rooms","3-day full home interiors","Low-VOC paint options"], serviceArea:"South Bay — Chula Vista, National City, Bonita, Imperial Beach" },

  // — CONCRETE ----------------------------------------------------------------
  { id:"dc21", initials:"CM", avatarBg:"#E6F1FB", avatarColor:"#185FA5", name:"Carlos Mendez",     company:"Mendez Concrete Works",          trades:["Concrete"],           city:"San Diego",      rating:4.8, reviewCount:52, years:20, licensed:true,  insured:true,  backgroundCheck:false, bio:"Concrete specialist for residential driveways, patios, pool decks, and foundations. 20 years in San Diego — we understand the soil conditions, the slope challenges, and the permit requirements by city.", highlights:["Decorative & stamped concrete","Driveway pour & replacement","Retaining walls & steps"], serviceArea:"All of San Diego County" },
  { id:"dc22", initials:"AC", avatarBg:"#E6F1FB", avatarColor:"#185FA5", name:"Alfonso Cruz",      company:"Cruz Concrete & Masonry",        trades:["Concrete"],           city:"National City",  rating:4.6, reviewCount:39, years:17, licensed:true,  insured:true,  backgroundCheck:false, bio:"Concrete and masonry contractor specializing in block walls, foundation repairs, and commercial slabs. Reliable and straightforward — most jobs estimated within 48 hours of contact.", highlights:["Block & retaining walls","Foundation crack repair","Commercial slab work"], serviceArea:"South Bay & Central SD — National City, Chula Vista, San Diego" },

  // — LANDSCAPING -------------------------------------------------------------
  { id:"dc23", initials:"SP", avatarBg:"#E1F5EE", avatarColor:"#0F6E56", name:"Sarah Park",        company:"Park Landscape Design",          trades:["Landscaping"],        city:"La Mesa",        rating:4.9, reviewCount:44, years:9,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Certified landscape designer focused on drought-tolerant, California-native gardens. Every design balances aesthetics with San Diego's water reality — most clients see 40-60% water reduction after install.", highlights:["Drought-tolerant native plants","Drip irrigation design","HOA-compliant plant palettes"], serviceArea:"East County — La Mesa, El Cajon, Lemon Grove, Santee" },
  { id:"dc24", initials:"MG", avatarBg:"#E1F5EE", avatarColor:"#0F6E56", name:"Maria Gonzalez",    company:"Gonzalez Landscape & Hardscape", trades:["Landscaping"],        city:"San Diego",      rating:4.6, reviewCount:55, years:10, licensed:true,  insured:true,  backgroundCheck:false, bio:"Full-service landscape and hardscape contractor for Central San Diego. Specializes in artificial turf installation, concrete patios, and retaining walls — one crew for outdoor work start to finish.", highlights:["Artificial turf specialist","Retaining walls & drainage","Concrete patios & walkways"], serviceArea:"Central SD — Mission Valley, North Park, Hillcrest, Kensington, Normal Heights" },
  { id:"dc25", initials:"RK", avatarBg:"#E1F5EE", avatarColor:"#0F6E56", name:"Rachel Kim",        company:"Green Thumb San Diego",          trades:["Landscaping"],        city:"La Jolla",       rating:4.9, reviewCount:18, years:5,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Landscape designer serving coastal North San Diego with a focus on low-maintenance, high-impact garden design. Especially experienced with HOA communities and Coastal Commission-adjacent properties.", highlights:["Coastal & HOA landscape design","Succulents & low-water gardens","Irrigation controller upgrades"], serviceArea:"Coastal SD — La Jolla, Del Mar, Pacific Beach, Encinitas, Solana Beach" },

  // — SOLAR -------------------------------------------------------------------
  { id:"dc26", initials:"NB", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Nathan Berg",       company:"Berg Solar Systems",             trades:["Solar"],              city:"San Diego",      rating:4.8, reviewCount:33, years:6,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Residential solar specialist focused exclusively on rooftop PV systems and battery backup. All designs are NEM 3.0 compliant with battery self-consumption modeling included in every proposal.", highlights:["NEM 3.0 self-consumption modeling","IQ8 microinverter specialist","Battery-first system design"], serviceArea:"San Diego, La Jolla, Pacific Beach, Ocean Beach, Point Loma" },

  // — POOL --------------------------------------------------------------------
  { id:"dc27", initials:"DT", avatarBg:"#E6F1FB", avatarColor:"#185FA5", name:"Diana Torres",      company:"Torres Pool & Spa",              trades:["Pool"],               city:"Chula Vista",    rating:4.9, reviewCount:36, years:14, licensed:true,  insured:true,  backgroundCheck:true,  bio:"C-53 licensed pool contractor specializing in custom gunite pools and spas for South Bay homes. We handle permitting, structural engineering, and the full build — single point of contact throughout.", highlights:["Custom gunite pools & spas","Full permitting & engineering included","Pool equipment upgrades"], serviceArea:"South Bay — Chula Vista, Bonita, National City, Coronado, San Diego" },
  { id:"dc28", initials:"KB", avatarBg:"#E6F1FB", avatarColor:"#185FA5", name:"Kevin Brandt",      company:"Brandt Pool Construction",       trades:["Pool"],               city:"El Cajon",       rating:4.7, reviewCount:28, years:16, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Custom pool builder with 16 years in East and Central San Diego. Known for creative freeform designs and consistent timelines. 3D pool renderings provided before any contracts are signed.", highlights:["3D pool rendering before contract","Freeform & lagoon designs","Spa & water feature integration"], serviceArea:"East & Central SD — El Cajon, Santee, La Mesa, San Diego, Lemon Grove" },
  { id:"dc29", initials:"AF", avatarBg:"#E6F1FB", avatarColor:"#185FA5", name:"Amanda Flores",     company:"Flores Aquatic Design",          trades:["Pool"],               city:"San Diego",      rating:4.8, reviewCount:21, years:11, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Pool design and construction specialist for North and Coastal San Diego. Particularly experienced with hillside lots, zero-edge designs, and properties subject to Coastal Commission review.", highlights:["Coastal Commission experience","Zero-edge & infinity pools","Solar heating & automation"], serviceArea:"Coastal SD — San Diego, La Jolla, Del Mar, Encinitas, Carlsbad" },

  // — WINDOWS -----------------------------------------------------------------
  { id:"dc30", initials:"MJ", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Marcus Johnson",    company:"All-Season Windows & Insulation",trades:["Windows","Insulation"],city:"Spring Valley",  rating:4.7, reviewCount:29, years:11, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Window replacement and insulation contractor helping San Diego homeowners lower SDG&E bills. Milgard Certified Dealer — most whole-home window projects completed in a single day.", highlights:["Milgard Certified Dealer","Whole-home window replacement","SDG&E energy rebate assistance"], serviceArea:"East & South County — Spring Valley, Lemon Grove, El Cajon, Bonita" },
  { id:"dc31", initials:"BN", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Bill Nguyen",       company:"Nguyen Window & Door Co.",       trades:["Windows"],            city:"San Diego",      rating:4.8, reviewCount:42, years:14, licensed:true,  insured:true,  backgroundCheck:false, bio:"Window and door replacement specialist serving Central and North San Diego. Vinyl, fiberglass, and aluminum frame options — Low-E glass standard on every install for coastal UV protection.", highlights:["Low-E coastal glass specialist","Sliding & French door replacement","Same-day window installs available"], serviceArea:"Central & North SD — San Diego, Kearny Mesa, Mission Valley, Poway" },
  { id:"dc32", initials:"PS", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Patricia Soto",     company:"Soto Glass & Window",            trades:["Windows"],            city:"Chula Vista",    rating:4.7, reviewCount:23, years:8,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Window specialist for South Bay with a focus on impact-resistant and dual-pane energy upgrades. Works with most homeowner insurance providers for storm damage replacements.", highlights:["Impact-resistant glass options","Insurance claim coordination","Energy Star certified windows"], serviceArea:"South Bay — Chula Vista, National City, Imperial Beach, Coronado" },

  // — FRAMING -----------------------------------------------------------------
  { id:"dc33", initials:"RC", avatarBg:"#EEEDFE", avatarColor:"#534AB7", name:"Ryan Carmichael",   company:"Carmichael Framing & Structure",trades:["Framing"],             city:"Escondido",      rating:4.8, reviewCount:26, years:15, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Structural framing contractor for room additions, ADUs, and custom home builds in North County. Tight schedules and clean sites — GCs keep calling us back because we don't create problems for other trades.", highlights:["Room additions & ADUs","Wood & steel stud framing","Tight scheduling for GC coordination"], serviceArea:"North County — Escondido, San Marcos, Vista, Carlsbad, Oceanside" },
  { id:"dc34", initials:"JR", avatarBg:"#EEEDFE", avatarColor:"#534AB7", name:"Jose Ramirez",      company:"Ramirez Framing Inc.",           trades:["Framing"],            city:"Chula Vista",    rating:4.6, reviewCount:33, years:10, licensed:true,  insured:true,  backgroundCheck:false, bio:"Residential framing specialist for South Bay and Central San Diego. Experienced with San Diego's seismic requirements and hillside lot challenges — every frame engineered to code.", highlights:["Seismic-compliant framing","Hillside & slope lot experience","New construction & additions"], serviceArea:"South Bay & Central SD — Chula Vista, National City, San Diego, Bonita" },

  // — INSULATION --------------------------------------------------------------
  { id:"dc35", initials:"GW", avatarBg:"#F8F7F4", avatarColor:"#5F5E5A", name:"Gary Whitfield",    company:"Whitfield Insulation Co.",       trades:["Insulation"],         city:"Spring Valley",  rating:4.7, reviewCount:31, years:13, licensed:true,  insured:true,  backgroundCheck:false, bio:"Insulation contractor for residential attics, walls, and crawl spaces in South and East County. R-38+ blown-in installs completed in under a day — most homeowners see lower energy bills within the first billing cycle.", highlights:["R-38+ blown-in attic insulation","Crawl space encapsulation","Title 24 compliance documentation"], serviceArea:"East & South County — Spring Valley, Lemon Grove, El Cajon, Bonita, Chula Vista" },
  { id:"dc36", initials:"DP", avatarBg:"#F8F7F4", avatarColor:"#5F5E5A", name:"Diane Park",        company:"Park Energy Solutions",          trades:["Insulation"],         city:"Poway",          rating:4.9, reviewCount:17, years:7,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Energy efficiency contractor specializing in spray foam and blown-in insulation for North County homes. SDG&E approved contractor — we handle all rebate applications from initial assessment to final payment.", highlights:["Closed-cell spray foam specialist","SDG&E rebate processing included","Whole-home energy assessments"], serviceArea:"North County — Poway, Rancho Bernardo, Rancho Penasquitos, Mira Mesa, Scripps Ranch" },

  // — DEMOLITION --------------------------------------------------------------
  { id:"dc37", initials:"FD", avatarBg:"#FCEBEB", avatarColor:"#A32D2D", name:"Frank Delgado",     company:"Delgado Demolition & Haul",      trades:["Demolition","Trucking"],city:"National City", rating:4.5, reviewCount:33, years:19, licensed:true,  insured:true,  backgroundCheck:false, bio:"Demolition and debris hauling specialist for residential and commercial projects. Interior gut jobs, detached structure removal, and site cleanouts — we clear the way so your contractor can start on day one.", highlights:["Interior gut & structure demo","Debris hauling & dumpster service","Asbestos survey coordination"], serviceArea:"All of San Diego County" },
  { id:"dc38", initials:"AH", avatarBg:"#FCEBEB", avatarColor:"#A32D2D", name:"Alex Hernandez",    company:"Precision Demo Inc.",            trades:["Demolition"],         city:"San Diego",      rating:4.7, reviewCount:24, years:16, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Licensed demolition contractor for selective interior demo, kitchen and bath teardowns, and small structure removal. Known for protecting adjacent structures — we don't damage what's staying.", highlights:["Selective & surgical demo","Kitchen & bath teardowns","Concrete breaking & removal"], serviceArea:"Central & North SD — San Diego, Mission Valley, La Jolla, Kearny Mesa" },

  // — ASPHALT -----------------------------------------------------------------
  { id:"dc39", initials:"MB", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Mike Battaglia",    company:"Battaglia Asphalt & Paving",     trades:["Asphalt"],            city:"San Diego",      rating:4.8, reviewCount:46, years:21, licensed:true,  insured:true,  backgroundCheck:false, bio:"Asphalt paving and sealing contractor for residential driveways and commercial parking lots. 21 years in San Diego — we know the climate, the substrate, and which products actually last in SoCal heat.", highlights:["Driveway replace & overlay","Parking lot seal & stripe","Crack fill & pothole repair"], serviceArea:"All of San Diego County" },
  { id:"dc40", initials:"RD", avatarBg:"#F1EFE8", avatarColor:"#2C2C2A", name:"Ray Dominguez",     company:"Dominguez Paving Co.",           trades:["Asphalt"],            city:"Chula Vista",    rating:4.6, reviewCount:29, years:12, licensed:true,  insured:true,  backgroundCheck:false, bio:"South Bay asphalt contractor specializing in residential driveway resurfacing and HOA parking lot maintenance. Free asphalt condition assessment before any quote — no pressure, no upsell.", highlights:["Free asphalt condition assessment","HOA parking lot maintenance","ADA-compliant ramp installs"], serviceArea:"South Bay — Chula Vista, National City, Bonita, Imperial Beach, Coronado" },

  // — LOCKSMITH ---------------------------------------------------------------
  { id:"dc41", initials:"EC", avatarBg:"#E6F1FB", avatarColor:"#0C447C", name:"Eric Coleman",      company:"Coleman Lock & Security",        trades:["Locksmith"],          city:"San Diego",      rating:4.8, reviewCount:62, years:9,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Licensed locksmith and security specialist serving Central San Diego. Residential rekeying, smart lock installation, and full home security upgrades. Move-in rekeys completed same day — usually within 2 hours of call.", highlights:["Same-day move-in rekeys","Smart lock & keypad installs","Schlage & Kwikset certified"], serviceArea:"Central SD — San Diego, North Park, Hillcrest, Mission Valley, University City" },
  { id:"dc42", initials:"SP", avatarBg:"#E6F1FB", avatarColor:"#0C447C", name:"Sandra Perez",      company:"Perez Security Solutions",       trades:["Locksmith"],          city:"El Cajon",       rating:4.7, reviewCount:38, years:7,  licensed:true,  insured:true,  backgroundCheck:true,  bio:"Residential locksmith serving East County with specialties in smart home security integration, access control systems, and emergency lockout service. Average response time under 45 minutes.", highlights:["Smart home security integration","Access control systems","45-min emergency response"], serviceArea:"East County — El Cajon, Santee, La Mesa, Spring Valley, Lakeside" },
  { id:"dc43", initials:"VO", avatarBg:"#E6F1FB", avatarColor:"#0C447C", name:"Victor Osei",       company:"Osei Lock & Safe",               trades:["Locksmith"],          city:"San Diego",      rating:4.9, reviewCount:19, years:14, licensed:true,  insured:true,  backgroundCheck:true,  bio:"Commercial and residential locksmith with 14 years of experience. Safe installation and combination changes, high-security deadbolt upgrades, and master key system design for multi-unit properties.", highlights:["High-security deadbolt upgrades","Safe install & combination changes","Master key systems for multi-units"], serviceArea:"San Diego, La Jolla, Pacific Beach, Ocean Beach, Point Loma, Downtown" },

  // — TRUCKING ----------------------------------------------------------------
  { id:"dc44", initials:"TW", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Terry Walsh",       company:"Walsh Hauling & Delivery",       trades:["Trucking"],           city:"National City",  rating:4.6, reviewCount:27, years:11, licensed:true,  insured:true,  backgroundCheck:false, bio:"Construction material delivery and debris hauling across San Diego County. Flatbed, dump truck, and roll-off dumpster service — coordinated delivery scheduling to match your contractor's timeline.", highlights:["Flatbed & dump truck service","Roll-off dumpster rental","Coordinated GC delivery scheduling"], serviceArea:"All of San Diego County" },
  { id:"dc45", initials:"LA", avatarBg:"#FAEEDA", avatarColor:"#854F0B", name:"Luis Avila",        company:"Pacific Haul Co.",               trades:["Trucking"],           city:"San Diego",      rating:4.7, reviewCount:21, years:8,  licensed:true,  insured:true,  backgroundCheck:false, bio:"Site material hauling and cleanout service for construction and remodeling projects. Fast dispatch, reliable scheduling — contractors use us repeatedly because we show up when we say we will.", highlights:["Same-day dispatch available","Construction site cleanouts","Soil, gravel & concrete hauling"], serviceArea:"San Diego, Chula Vista, El Cajon, La Mesa, National City" },
];


export const DEMO_ACCOUNTS = [
  {
    email:           "demo@buildconnectpro.com",
    password:        "BuildConnect2024",
    role:            "contractor",
    name:            "Mike Sandoval",
    company:         "Sandoval Electric",
    city:            "National City",
    state:           "CA",
    trades:          ["Electrical"],
    years:           "22",
    licensed:        true,
    insured:         true,
    backgroundCheck: true,
    bio:             "San Diego native and C-10 licensed electrician specializing in residential panel upgrades, EV charger installation, and service upgrades. 22 years of clean, code-compliant work across South Bay. Known for showing up on time, keeping job sites clean, and communicating clearly at every step.",
    phone:           "(619) 555-0182",
    website:         "www.sandovalelectric.com",
    licenseNum:      "C10-1049821",
    insurance:       "State Farm General Liability — $2M coverage",
    serviceArea:     "South Bay — National City, Chula Vista, Bonita, San Diego, Coronado",
    plan:            "professional",
  },
  {
    email:    "homeowner@buildconnectpro.com",
    password: "BuildConnect2024",
    role:     "consumer",
    name:     "Sarah Mitchell",
    phone:    "(619) 555-0247",
    city:     "Chula Vista",
    state:    "CA",
  },
];
